### ISSUE TITLE
Data Filtering

### ISSUE THREAD

**Issue by wuhc1010** [neonbjb/tortoise-tts#334]
Hi, neonbjb

tortoise is amazing, I'm trying to reproduce it. 
could you share something aboud the tools(or ML models) for detecting noise/background music in speech audio

Thanks!

**Comment by szprytny** [comment]
Hi @neonbjb,

 Is this something you could share?

> I then fed the resulting clips through a pipeline of classifiers that I trained which remove any audio with background noise, music, poor quality (such as phone calls), multiple voices speaking at once and reverb. 

I tried to look for some public classifiers for this task but unfortunatelly I cannot find any. I would appreciate any tips regarding building such classifier if you cannot share ones you've built.

Thanks in advance!

**Comment by neonbjb** [comment]
Hey guys,
I'm happy to share this - I just have not found the time to wrap it up in a nice package so that others can use it easily.

How about this: I'll provide all the scripts and models to you and in exchange, you'll clean them up and put together a github/huggingface repo and write up some documentation for how to use them.

**Comment by szprytny** [comment]
Sounds good :) 
I just want to point that I am not experienced in python development, especially in creating packages / using good coding practices nor have any experience with huggingface, so that seems like a good excercise. I would appreciate some help / guidance.

**Comment by neonbjb** [comment]
The script that does the filtering can be found here:
https://github.com/neonbjb/DL-Art-School/blob/master/codes/scripts/audio/preparation/pipeline.py

You will need a few files:
1. Classifier weights, [here](https://drive.google.com/file/d/1Mg5ok2Es7utGDvWzwX_pjugDKzhrTT9q/view?usp=share_link)
2. Classifier config, [here](https://drive.google.com/file/d/1eWDW1LalRe4W7HaomhjuDHt4LSnOuKDa/view?usp=share_link)
3. CLVP (which comes with tortoise)

I'd recommend you clone DLAS first and just try and run the pipeline against a local folder full of audio files without tweaking anything, so you can get a feel for how it works. Then try stripping it out of DLAS into its own repo. You can upload the model weights for CLVP and the classifier onto the huggingface hub like I did with Tortoise.

Thanks for the help, let me know if I forgot anything!

**Comment by eschmidbauer** [comment]
i took some time to package the DL-Art-School repo a few weeks back.
you can access it [here](https://git.ecker.tech/eschmidbauer/dlas)
not sure if it will help here or not

**Comment by szprytny** [comment]
I have found some time to test this and then extracted classifier model to separate package, here is the link to it:

https://pypi.org/project/audclas/

**Comment by eschmidbauer** [comment]
> I have found some time to test this and then extracted classifier model to separate package, here is the link to it:
> 
> https://pypi.org/project/au

@szprytny 
Is this hosted on github somewhere? Im running into a crash with it when it can't label, I added this line to fix it.

![Screen Shot 2023-04-27 at 1 08 29 PM](https://user-images.githubusercontent.com/7139998/234937908-9eddf1df-0d18-4e32-b51f-5bb92ae52b84.png)

**Comment by Keith-Hon** [comment]
> I have found some time to test this and then extracted classifier model to separate package, here is the link to it:
> 
> https://pypi.org/project/audclas/

Seems the batch size affects the final output.

**Comment by acul3** [comment]
> The script that does the filtering can be found here: https://github.com/neonbjb/DL-Art-School/blob/master/codes/scripts/audio/preparation/pipeline.py
> 
> You will need a few files:
> 
> 1. Classifier weights, [here](https://drive.google.com/file/d/1Mg5ok2Es7utGDvWzwX_pjugDKzhrTT9q/view?usp=share_link)
> 2. Classifier config, [here](https://drive.google.com/file/d/1eWDW1LalRe4W7HaomhjuDHt4LSnOuKDa/view?usp=share_link)
> 3. CLVP (which comes with tortoise)
> 
> I'd recommend you clone DLAS first and just try and run the pipeline against a local folder full of audio files without tweaking anything, so you can get a feel for how it works. Then try stripping it out of DLAS into its own repo. You can upload the model weights for CLVP and the classifier onto the huggingface hub like I did with Tortoise.
> 
> Thanks for the help, let me know if I forgot anything!

@neonbjb i check for 3 stage of pipeline

it seems at to run pipelin stage 3 you need yaml config for voice clip  

https://github.com/neonbjb/DL-Art-School/blob/f31a333c4ff51eef9d5d4d1091fce7a610159b80/codes/scripts/audio/preparation/phase_3_generate_similarities.py#L108

is this clvp? or another model?

could your share the config 

thank you

**Comment by neonbjb** [comment]
This is CVVP: 
https://huggingface.co/jbetker/tortoise-tts-v2/blob/main/models/cvvp.py
https://huggingface.co/jbetker/tortoise-tts-v2/blob/main/.models/cvvp.pth

```
#### general settings
# Notes:
name: train_cvvp
use_tb_logger: true
gpu_ids: [0]
start_step: 0
fp16: true
checkpointing_enabled: true  
wandb: true
wandb_project_name: train_cvvp
wandb_run_name: r0

datasets:
  train:
    name: clips
    n_workers: 8
    batch_size: 256
    mode: fast_paired_voice_audio
    sample_rate: 22050
    path: [y:/libritts/train-other-500/transcribed-oco-realtext.tsv,
           y:/libritts/train-clean-100/transcribed-oco-realtext.tsv,
           y:/libritts/train-clean-360/transcribed-oco-realtext.tsv,
           y:/clips/podcasts-0/transcribed-oco.tsv,
           y:/clips/books1/transcribed-oco.tsv,
           y:/clips/books2/transcribed-oco.tsv,
	       y:/bigasr_dataset/hifi_tts/transcribed-oco-realtext.tsv,
           y:/clips/podcasts-0/transcribed-oco.tsv,
           #y:/clips/podcasts-1/transcribed-oco.tsv,
           ]
    max_wav_length: 160000  # Extend this in later stages of training.
    max_text_length: 200
    load_conditioning: true
    num_conditioning_candidates: 1
    conditioning_length: 160000
    use_bpe_tokenizer: true
    load_aligned_codes: false
  val:
    name: mass_test
    n_workers: 1
    batch_size: 16
    mode: paired_voice_audio
    sample_rate: 22050
    path: [y:/bigasr_dataset/librispeech/val/val.txt]
    fetcher_mode: [libritts]
    max_wav_length: 160000
    max_text_length: 200
    load_conditioning: true
    num_conditioning_candidates: 1
    conditioning_length: 102400
    needs_collate: false
    use_bpe_tokenizer: true

networks:
  cvvp:
    type: generator
    which_model_G: cvvp
    kwargs:
      model_dim: 512
      transformer_heads: 8
      dropout: .1
      mel_codes: 8192
      conditioning_enc_depth: 8
      cond_mask_percentage: .15
      speech_enc_depth: 8
      speech_mask_percentage: .15
      latent_multiplier: 1

#### path
path:
  strict_load: true
  resume_state: ../experiments/train_cvvp/training_state/29750.state

steps:        
  clvp_train:
    training: cvvp
    loss_log_buffer: 500

    optimizer: adamw
    optimizer_params:
      lr: !!float 1e-4
      weight_decay: !!float 1e-3
      beta1: 0.9
      beta2: 0.99
    #clip_grad_eps: 1

    injectors:
      speech_to_mel:
        type: torch_mel_spectrogram
        mel_norm_file: ../experiments/clips_mel_norms.pth
        in: wav
        out: mel
      to_codes:
        type: discrete_token
        in: mel
        out: mel_codes
      cond_to_mel:
        type: torch_mel_spectrogram
        mel_norm_file: ../experiments/clips_mel_norms.pth
        in: conditioning
        out: cond_mel
      clvp_fwd:
        type: generator
        generator: cvvp
        in: [mel_codes, cond_mel, true]
        out: cvvp_loss
    losses:
      cvvp:
        type: direct
        weight: 1
        key: cvvp_loss
      

train:
  niter: 500000
  warmup_iter: -1
  mega_batch_factor: 1
  val_freq: 2000
  sort_key: wav_lengths
  auto_collate: true

  default_lr_scheme: MultiStepLR
  gen_lr_steps: [ 20000, 40000, 60000 ]
  lr_gamma: 0.2
  warmup_steps: 1000
  #force_lr: !!float 2e-5

eval:
  pure: true

logger:
  print_freq: 5
  save_checkpoint_freq: 250
  visuals: []
  is_mel_spectrogram: true
  visual_debug_rate: 100
```
